.default: &default
  only:
    - merge_requests
    - web

.default_tag: &default_tag
  tags:
    - backend-docker-large

image: docker.phonepe.com:5000/pp-maven:3.8.4-openjdk-17

stages:
  - build
  - deploy

"Build Snapshot":
  stage: build
  <<: *default
  <<: *default_tag
  script:
    - mvn package -U -DskipTests=true -Denforcer.skip


"Deploy Snapshot":
  stage: deploy
  <<: *default_tag
  <<: *default
  allow_failure: false
  script:
    - mvn deploy -U -DskipTests=true -Denforcer.skip
  when: manual
